### ISSUE TITLE
turnメソッドの実行に必要なqueryオブジェクトを簡単に作れない

### ISSUE THREAD

**Issue by kamataryo** [KamataRyo/node-miopon#2]
現在は、仕様書を見てJSONを組み立てる以外は、下記の手順でしかqueryオブジェクト送信できない。（turnまでにリクエストの発行が２回必要）
1. informメソッドでinformationオブジェクトを取得
2. querifyメソッドでqueryオブジェクトに変換

hdoServiceCodeを直指定してqueryオブジェクトを生成する方法を実装するべき。

**Comment by KamataRyo** [comment]
generateQueryとして実装開始
https://github.com/KamataRyo/node-miopon/commit/fd4c3abcbadaeea65f15db2dd169fb368d98bee8

**Comment by kamataryo** [comment]
done
https://github.com/KamataRyo/node-miopon/commit/2a5c1960191cea16fad97c3aa5e706a2bebaaef6
